In [45]:
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

import numpy as np

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [46]:
#importando dataframe
dataframe = pd.read_csv("/content/bottle.csv", on_bad_lines='skip')
#Mostrando colunas
dataframe.columns

<ipython-input-46-42de0b17d336>:2: DtypeWarning: Columns (47,73) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe = pd.read_csv("/content/bottle.csv", on_bad_lines='skip')

Index(['Cst_Cnt', 'Btl_Cnt', 'Sta_ID', 'Depth_ID', 'Depthm', 'T_degC',
       'Salnty', 'O2ml_L', 'STheta', 'O2Sat', 'Oxy_µmol/Kg', 'BtlNum',
       'RecInd', 'T_prec', 'T_qual', 'S_prec', 'S_qual', 'P_qual', 'O_qual',
       'SThtaq', 'O2Satq', 'ChlorA', 'Chlqua', 'Phaeop', 'Phaqua', 'PO4uM',
       'PO4q', 'SiO3uM', 'SiO3qu', 'NO2uM', 'NO2q', 'NO3uM', 'NO3q', 'NH3uM',
       'NH3q', 'C14As1', 'C14A1p', 'C14A1q', 'C14As2', 'C14A2p', 'C14A2q',
       'DarkAs', 'DarkAp', 'DarkAq', 'MeanAs', 'MeanAp', 'MeanAq', 'IncTim',
       'LightP', 'R_Depth', 'R_TEMP', 'R_POTEMP', 'R_SALINITY', 'R_SIGMA',
       'R_SVA', 'R_DYNHT', 'R_O2', 'R_O2Sat', 'R_SIO3', 'R_PO4', 'R_NO3',
       'R_NO2', 'R_NH4', 'R_CHLA', 'R_PHAEO', 'R_PRES', 'R_SAMP', 'DIC1',
       'DIC2', 'TA1', 'TA2', 'pH2', 'pH1', 'DIC Quality Comment'],
      dtype='object')

In [47]:
#Mostrando informações do dataframe
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883816 entries, 0 to 883815
Data columns (total 74 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Cst_Cnt              883816 non-null  int64
 1   Btl_Cnt              883816 non-null  int64
 2   Sta_ID               883815 non-null  object
 3   Depth_ID             883815 non-null  object
 4   Depthm               883815 non-null  float64
 5   T_degC               872703 non-null  float64
 6   Salnty               835834 non-null  float64
 7   O2ml_L               713690 non-null  float64
 8   STheta               830367 non-null  float64
 9   O2Sat                678077 non-null  float64
 10  Oxy_µmol/Kg          678072 non-null  float64
 11  BtlNum               118668 non-null  float64
 12  RecInd               883812 non-null  float64
 13  T_prec               872696 non-null  float64
 14  T_qual               23336 non-null   float64
 15  S_prec               835828 non-null  float64
 16  S_qual               75670 non-null   float64
 17  P_qual               692701 non-null  float64
 18  O_qual               186221 non-null  float64
 19  SThtaq               66755 non-null   float64
 20  O2Satq               220159 non-null  float64
 21  ChlorA               225275 non-null  float64
 22  Chlqua               658110 non-null  float64
 23  Phaeop               225274 non-null  float64
 24  Phaqua               658116 non-null  float64
 25  PO4uM                427026 non-null  float64
 26  PO4q                 457023 non-null  float64
 27  SiO3uM               354095 non-null  float64
 28  SiO3qu               529810 non-null  float64
 29  NO2uM                337579 non-null  float64
 30  NO2q                 548419 non-null  float64
 31  NO3uM                337404 non-null  float64
 32  NO3q                 548879 non-null  float64
 33  NH3uM                64964 non-null   float64
 34  NH3q                 827244 non-null  float64
 35  C14As1               14435 non-null   float64
 36  C14A1p               12762 non-null   float64
 37  C14A1q               867550 non-null  float64
 38  C14As2               14417 non-null   float64
 39  C14A2p               12744 non-null   float64
 40  C14A2q               867568 non-null  float64
 41  DarkAs               22652 non-null   float64
 42  DarkAp               20458 non-null   float64
 43  DarkAq               859385 non-null  float64
 44  MeanAs               22652 non-null   float64
 45  MeanAp               20460 non-null   float64
 46  MeanAq               859385 non-null  float64
 47  IncTim               14439 non-null   object
 48  LightP               18654 non-null   float64
 49  R_Depth              883811 non-null  float64
 50  R_TEMP               872698 non-null  float64
 51  R_POTEMP             836944 non-null  float64
 52  R_SALINITY           835831 non-null  float64
 53  R_SIGMA              830022 non-null  float64
 54  R_SVA                830108 non-null  float64
 55  R_DYNHT              836527 non-null  float64
 56  R_O2                 713684 non-null  float64
 57  R_O2Sat              683283 non-null  float64
 58  R_SIO3               354100 non-null  float64
 59  R_PO4                427031 non-null  float64
 60  R_NO3                337413 non-null  float64
 61  R_NO2                337584 non-null  float64
 62  R_NH4                64983 non-null   float64
 63  R_CHLA               225276 non-null  float64
 64  R_PHAEO              225276 non-null  float64
 65  R_PRES               883806 non-null  float64
 66  R_SAMP               122006 non-null  float64
 67  DIC1                 1999 non-null    float64
 68  DIC2                 224 non-null     float64
 69  TA1                  2084 non-null    float64
 70  TA2                  234 non-null     float64
 71  pH2                  10 non-null      float64
 72  pH1                  84 non-null      float64
 73  DIC Quality Comment  55 non-null      object
dtypes: float64(68), int64(2), object(4)
memory usage: 499.0+ MB

In [48]:
#Mostrando 5 primeiras linhas do dataframe
dataframe.head()

,Cst_Cnt,Btl_Cnt,Sta_ID,Depth_ID,Depthm,T_degC,Salnty,O2ml_L,STheta,O2Sat,...,R_PHAEO,R_PRES,R_SAMP,DIC1,DIC2,TA1,TA2,pH2,pH1,DIC Quality Comment
0,1,1,054.0 056.0,19-4903CR-HY-060-0930-05400560-0000A-3,0.0,10.50,33.440,NaN,25.649,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,054.0 056.0,19-4903CR-HY-060-0930-05400560-0008A-3,8.0,10.46,33.440,NaN,25.656,NaN,...,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,054.0 056.0,19-4903CR-HY-060-0930-05400560-0010A-7,10.0,10.46,33.437,NaN,25.654,NaN,...,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,054.0 056.0,19-4903CR-HY-060-0930-05400560-0019A-3,19.0,10.45,33.420,NaN,25.643,NaN,...,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,054.0 056.0,19-4903CR-HY-060-0930-05400560-0020A-7,20.0,10.45,33.421,NaN,25.643,NaN,...,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
#Verificando se há valores vazios
df = dataframe

df.isnull().values.any()

True

In [50]:
#Removendo linhas com valores vazios
df = df.dropna()

In [51]:
#Alterando nome das colunas que serão utilizadas
df = dataframe.rename(columns ={'T_degC':'Temperatura', 'Salnty': 'Salinidade'})
df = df[['Temperatura','Salinidade']]
df.head()

   Temperatura  Salinidade
0        10.50      33.440
1        10.46      33.440
2        10.46      33.437
3        10.45      33.420
4        10.45      33.421

In [52]:
scaler = StandardScaler()

# Aplicando o método fit_transform() do objeto scaler nos dados do DataFrame df
# Ajusta a escala dos dados
scaled_data = scaler.fit_transform(df)

# Removendo as linhas que contêm valores NaN (valores ausentes) do array de dados escalonados
# Utilizando a função numpy np.isnan() para identificar valores NaN e a função any(axis=1) para identificar linhas que contenham pelo menos um valor NaN
scaled_data_sem_nan = scaled_data[~np.isnan(scaled_data).any(axis=1)]

In [53]:
# Dividindo os dados em conjuntos de treinamento e teste
x_train, x_test, y_train, y_test = train_test_split(scaled_data_sem_nan[:,0], scaled_data_sem_nan[:,1], test_size=0.30, random_state=42)

In [56]:
#Aplicação da regressão linear e treino do modelo

ia = LinearRegression()

ia.fit(x_train.reshape(-1,1), y_train)

y_hat = ia.predict(x_test.reshape(-1,1))

# Calcular R²
r2 = r2_score(y_test, y_hat)

# Calcular MAE
mae = mean_absolute_error(y_test, y_hat)

# Calcular MSE
mse = mean_squared_error(y_test, y_hat)

# Calcular RMSE
rmse = np.sqrt(mse)
print(y_hat[:10])
print(y_test[:10])

print(f'R²: {r2:.2f}')
print(f'MAE: {mae:.2f}')
print(f'MSE: {mse:.2f}')
print(f'RMSE: {rmse:.2f}')

[-7.17454761e-01  4.37152632e-01 -6.45962043e-01 -3.81438987e-01
 -4.38633162e-01  3.16329939e-01  1.67863395e-01  1.97652027e-01
 -1.44492337e-04 -7.42477212e-01]
[-0.58092631  0.42804945 -0.65606281 -1.82604534 -0.70973173  0.40765526
  0.45595729 -0.08717222 -0.23315169 -0.49505604]
R²: 0.26
MAE: 0.60
MSE: 0.75
RMSE: 0.86

In [ ]:
plt.figure(figsize=(8, 6))
sns.regplot(x='Temperatura', y='Salinidade', data=df, ci=None, scatter_kws={'color':'green'}, line_kws={'color':'red'})
plt.title('Regressão Linear')
plt.xlabel('Temperatura')
plt.ylabel('Salinidade')
plt.grid(True)
plt.show()

In [ ]:
print("Coeficiente linear (intercept):", ia.intercept_)
print("Coeficiente angular (slope):", ia.coef_)